# Generated by Django 4.0.4 on 2022-05-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliation',
            unique_together={('email', 'course')},
        ),
    ]
